### ISSUE TITLE
Frontend: Como usuario: "Quiero poder crear una lista de películas para verlas luego, sin necesidad de buscarlas nuevamente. Quiero que mi información esté disponible cuando inicio sesión

### ISSUE THREAD

**Issue by AdriCabrera** [4GeeksAcademy/Latam-pt-30-AdriCabrera-Movie-Generator-Final-Project#19]
### Lista de películas

- [ ] En el landing page principal las películas deben tener un botón que sea agregar a la lista
- [ ] **"Mi lista"** debe aparecer en el navbar
- [ ] Debo poder quitar selección de **"Mi lista"**

**Comment by Mitronios** [comment]
- [ ] Añadir botones de agregar película en las vistas de recomendado, mi lista, peliculas y vista especifica
